name: CI

on: [ push ]

jobs:
  upload:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      # Integration tests gets stuck in Github while running verify; can't enable it here right now.
      - name: Run CI
        run: mvn --batch-mode -Pintegration clean package
