name: Upload Release

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build
        run: |
          mvn -B -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean verify package;
          mvn -B -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean package -f rpm.pom.xml;
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Attach rpm as artifact on releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/rpm/com.teragrep-zep_01/RPMS/x86_64/com.teragrep-zep_01-*.x86_64.rpm
